# Generated by Django 4.2.5 on 2023-10-31 11:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_customuser_country_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='politicus_avatars/placeholder', max_length=255, verbose_name='image'),
        ),
    ]
