# Generated by Django 4.2.5 on 2023-10-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
