# Generated by Django 4.2.5 on 2023-10-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_alter_response_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
    ]
