# Generated by Django 4.2.5 on 2023-10-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together=set(),
        ),
    ]
